=== Sohammehta1/College_code/web/xml/assingment3/Employee.dtd
<!ELEMENT Business (company)>
<!ELEMENT company (Employee+)>
<!ATTLIST company cname ID #REQUIRED>
<!ELEMENT Employee (name,role, salary)>
<!ATTLIST Employee eid ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== Sohammehta1/College_code/web/xml/assingment3/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Business SYSTEM "Employee.dtd">
<?xml-stylesheet href="design.xsl" type="text/xsl"?>

<Business>
    <company cname ="Boat">
        <Employee eid ="e1">
            <name>Aman Gupta</name>
            <role>CEO</role>
            <salary>10000000</salary>
        </Employee>
        <Employee eid ="e2">
            <name>Soham Mehta</name>
            <role>CTO</role>
            <salary>10000000</salary>
        </Employee>
    </company>
</Business>
